const ERROR_CODES = {
  // Authentication & Session
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_PASSWORD_EXPIRED: 'AUTH_PASSWORD_EXPIRED',

  // RBAC & Scope
  FORBIDDEN_INSUFFICIENT_PERMISSIONS: 'FORBIDDEN_INSUFFICIENT_PERMISSIONS',
  FORBIDDEN_SCOPE_VIOLATION: 'FORBIDDEN_SCOPE_VIOLATION',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  // Resource & State
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Rate Limiting & Server
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

module.exports = { ERROR_CODES };
