const ROLES = {
  PLATFORM_OWNER: 'PLATFORM_OWNER',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  ACADEMIC_ADMIN: 'ACADEMIC_ADMIN',
  REGISTRAR: 'REGISTRAR',
  TEACHER: 'TEACHER',
  AUDITOR: 'AUDITOR'
};

const SCOPES = {
  PLATFORM: 'PLATFORM',
  SCHOOL: 'SCHOOL',
  SECTION: 'SECTION'
};

module.exports = { ROLES, SCOPES };
